### ISSUE TITLE
Change the default value for line length

### ISSUE THREAD

**Issue by Kabouik** [AtomLinter/linter-lintr#104]
Hi,

I would like to change the default value for the warning on line length, but I couldn't find how to edit that. I am using Atom with Rbox set to cut lines at 140 characters, but the linter warning still shows for lines longer than 80 characters. Is there a configuration file I can edit?

**Comment by Arcanemagus** [comment]
This would be coming from `lintr` itself, so you'll have to check its documentation for whether there is such an option.
