### ISSUE TITLE
Variable and Function Name and Commented Code

### ISSUE THREAD

**Issue by JLCCI** [AtomLinter/linter-lintr#43]
First of all, thank you so much for providing the linter, works great.

If it would not be a problem it would be fantastic if you could provide an option to turn off two of the lintr error messages. Specifically:

1) "Variable and function names should be all lowercase." While I do follow this in my own code, almost every single package from CRAN of Bioconductor I use does not. This makes half of my script highlighted as issue. 
2) "Commented code should be removed" For final source code you would like to avoid it, but a lot of people use R for exploratory data analysis and a lot of the code might be temporary commented out.

The default setting can of course stay as is, but I think a lot of people would really appreciate having an option to turn this off.

Many thanks and keep up the good work.

**Comment by Arcanemagus** [comment]
Is the [`lintr configuration file`](https://github.com/jimhester/lintr#project-configuration) not working for you?

**Comment by JLCCI** [comment]
Upss was not aware there is an option to customize lintr. Many thanks,
