### ISSUE TITLE
Ignore assignment_linter as global setting

### ISSUE THREAD

**Issue by sebastianbarfort** [AtomLinter/linter-lintr#74]
Hi,

I'm relatively new to Atom so I apologize if this question is too obvious. 

I can't figure out how to make `lintr` ignore `assignment_linter`. I tried so set

 `with_defaults(assignment_linter = NULL)` 

in the `Linters` box in *Atom -> Preferences -> Packages -> linter-lintr* but it doesn't seem to work. 

I want `assignment_linter = NULL` to be a global setting so I didn't try to create a `.lintr` file. 

Thanks for a great package,
Sebastian

**Comment by jimhester** [comment]
`with_defaults(assignment_linter = NULL)` does work fine for me and turns off the assignment linter as expected.

Could you run `library(lintr);devtools::session_info()` in a new R window, maybe there is something wrong on the R side.

**Comment by sebastianbarfort** [comment]
Hmm, I reinstalled the atom package and it seems to work now. Sorry to bother and thanks for the reply!
