### ISSUE TITLE
spawn R ENOENT

### ISSUE THREAD

**Issue by sgoley** [AtomLinter/linter-lintr#85]
Hi, Currently receiving this error. Atom version 1.13.0 ia32 / linter-lintr 1.1.1.

It doesn't prevent me from running code currently (I also have hydrogen installed) but it has this constant popup while I work. Any ideas?

<img width="227" alt="2017-01-19 08_34_17-" src="https://cloud.githubusercontent.com/assets/10283176/22108679/41c5ca2c-de22-11e6-9a21-707dfacecf31.png">

**Comment by IMLD** [comment]
Having this issue as well

**Comment by Arcanemagus** [comment]
Is `R` available in your `%PATH%`? If not you will need to set the _full_ path to it in your settings.

**Comment by IMLD** [comment]
`R` is available in my `%PATH%` as `C:\Program Files\R\R-3.3.2\bin`

**Comment by Arcanemagus** [comment]
@IMLD Then for some reason Atom isn't exposing a PATH that includes that, you'll need to set the full path (`C:\Program Files\R\R-3.3.2\bin\R.exe`) in the settings.

**Comment by IMLD** [comment]
This resolved the pop-up error box, but lintr is still not finding any errors. It always reports 'No Issues'.

**Comment by Arcanemagus** [comment]
Closing due to a lack of response from @sgoley. Hopefully the comments above resolving this for @IMLD help you, if not please comment further with any issues you are still having!
