### ISSUE TITLE
Extra new line error

### ISSUE THREAD

**Issue by Arcanemagus** [AtomLinter/linter-lintr#9]
Since 7ff6d0cad94afe3569944512609117a6889afaec no matter what appends a new line to a file, if the file _already_ has one at the end it will trigger a "Trailing blank lines are superfluous." error.

The extra new line should only be inserted if it wasn't already there.

Something like:
```coffeescript
fileText = textEditor.getText()
fileText += '\n' if not fileText.slice(-1).match(/\n/)
```

**Comment by jimhester** [comment]
Yeah that makes sense, maybe this, saves a regex call.
```coffeescript
fileText = textEditor.getText()
fileText += '\n' if fileText.slice(-1) isnt '\n'
```

**Comment by Arcanemagus** [comment]
That should work just fine, if the file is using CRLF it will still be `\r\n` at the end, so checking for `\n` works.

**Comment by Arcanemagus** [comment]
Thanks!
