### ISSUE TITLE
Process exited with no-zero code, stdout

### ISSUE THREAD

**Issue by wligtenberg** [AtomLinter/linter-lintr#90]
I recently started getting the following error:

```
~/.atom/packages/linter/lib/linter-registry.js:159 [Linter] Error running lintr Error: Process execution timed out
    at ~/.atom/packages/linter-lintr/node_modules/sb-exec/lib/index.js:92:18(anonymous function) @ ~/.atom/packages/linter/lib/linter-registry.js:159
~/.atom/packages/linter-lintr/node_modules/sb-exec/lib/index.js:59 [exec] Process exited with no-zero code, stdout:  
```

Linting still works though. But I do find the red boxes annoying. :)

**Comment by Arcanemagus** [comment]
Odd, that second one actually _shold_ be breaking it, i'll get a fix out shortly!

**Comment by Arcanemagus** [comment]
Both things should be addressed in v1.1.3, thanks for reporting!

**Comment by wligtenberg** [comment]
confirming that it is fixed.
Thanks for this useful package!

**Comment by Arcanemagus** [comment]
Since the specs were passing before ignoring the exit code was added, it seems it only throws an odd exit code in certain situations which is why it was working sometimes and not others.
